import { expect, test } from '@playwright/test';
import { resolve } from 'node:path';

test('real browser: send, refresh, persist, rename, archive and restore', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await expect(page.getByRole('button', { name: '发送消息' })).toBeVisible();
  await expect(page.getByText('本地已连接')).toBeVisible();
  await page.screenshot({ path: resolve('../.pi-agent/qa/welcome.png'), fullPage: true });
  await page.getByRole('textbox', { name: '输入消息' }).fill('读取 README.md 并告诉我它的内容。');
  await page.getByRole('button', { name: '发送消息' }).click();
  await expect(page.locator('.message.user')).toBeVisible();
  await page.reload();
  await expect(page.locator('.message.assistant')).toContainText('The web workbench reads real files.', { timeout: 15000 });
  await expect(page.locator('.activity-list')).toContainText('read 返回结果');
  await page.getByRole('button', { name: /read 返回结果/ }).click();
  await expect(page.getByRole('dialog', { name: '执行节点详情' })).toContainText('输入');
  await expect(page.getByRole('dialog', { name: '执行节点详情' })).toContainText('输出');
  await page.getByText('执行后快照').click();
  await expect(page.getByRole('dialog', { name: '执行节点详情' })).toContainText('tool_rounds');
  await page.getByRole('button', { name: '关闭节点详情' }).click();
  await expect(page.locator('.message.user')).toHaveCount(1);
  await expect(page.locator('.run-summary')).toContainText('已完成');
  await page.screenshot({ path: resolve('../.pi-agent/qa/conversation.png'), fullPage: true });
  await page.getByRole('button', { name: '会话操作' }).click();
  await page.getByRole('button', { name: '重命名', exact: true }).click();
  await page.getByLabel('会话名称').fill('浏览器联调');
  await page.getByRole('button', { name: '保存名称' }).click();
  await expect(page.locator('.breadcrumb')).toContainText('浏览器联调');
  await page.getByRole('button', { name: '会话操作' }).click();
  await page.getByRole('button', { name: '归档会话', exact: true }).click();
  await page.getByRole('button', { name: '已归档会话', exact: true }).click();
  await page.getByRole('button', { name: '浏览器联调', exact: true }).click();
  await expect(page.getByRole('button', { name: '恢复会话', exact: true })).toBeVisible();
  await page.getByRole('button', { name: '恢复会话', exact: true }).click();
  await page.getByRole('button', { name: '返回最近会话', exact: true }).click();
  await expect(page.getByRole('button', { name: '浏览器联调', exact: true })).toBeVisible();
  await page.getByRole('button', { name: '工作区与工具' }).click();
  await expect(page.getByRole('dialog', { name: '工作区与工具设置' })).toBeVisible();
  await page.getByRole('spinbutton', { name: 'read 最大调用次数' }).fill('7');
  await page.getByRole('checkbox', { name: /列出目录/ }).uncheck();
  await page.getByRole('checkbox', { name: /搜索文本/ }).uncheck();
  await page.getByRole('button', { name: '保存设置' }).click();
  await expect(page.locator('.tool-chips')).toContainText('read');
  await expect(page.locator('.tool-chips')).not.toContainText('search');
  await page.reload();
  await page.getByRole('button', { name: '工作区与工具' }).click();
  await expect(page.getByRole('spinbutton', { name: 'read 最大调用次数' })).toHaveValue('7');
  expect(errors).toEqual([]);
});

test('mobile layout, sidebar and safe rendering', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('/');
  await expect(page.getByText('本地已连接')).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(390);
  await page.getByRole('button', { name: '打开会话栏' }).click();
  await page.getByRole('button', { name: '新建会话' }).click();
  await page.getByRole('textbox', { name: '输入消息' }).fill('<img src=x onerror=alert(1)>');
  await page.getByRole('button', { name: '发送消息' }).click();
  await expect(page.locator('.run-summary')).toContainText('已完成', { timeout: 15000 });
  await expect(page.locator('.message.user img')).toHaveCount(0);
  await page.screenshot({ path: resolve('../.pi-agent/qa/mobile.png'), fullPage: true });
});

test('stop action is explicit and does not duplicate the prompt', async ({ page }) => {
  await page.goto('/');
  await page.getByRole('textbox', { name: '输入消息' }).fill('读取 README.md');
  await page.getByRole('button', { name: '发送消息' }).click();
  await page.getByRole('button', { name: '停止运行' }).click();
  await expect(page.locator('.run-summary')).toContainText('已停止', { timeout: 15000 });
  await page.reload();
  await expect(page.locator('.run-summary')).toContainText('已停止');
  await expect(page.locator('.message.user')).toHaveCount(1);
});
